# Generated by Django 5.0.2 on 2024-02-19 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.AutoField(db_column='Customer ID', primary_key=True, serialize=False)),
                ('first_name', models.CharField(db_column='First Name', max_length=100)),
                ('last_name', models.CharField(db_column='Last Name', max_length=100)),
                ('age', models.IntegerField(db_column='Age')),
                ('phone_number', models.BigIntegerField(db_column='Phone Number')),
                ('monthly_salary', models.IntegerField(db_column='Monthly Salary')),
                ('approved_limit', models.IntegerField(db_column='Approved Limit')),
            ],
            options={
                'db_table': 'customer_data',
            },
        ),
        migrations.CreateModel(
            name='LoanData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_id', models.IntegerField(db_column='Loan ID')),
                ('loan_amount', models.IntegerField(db_column='Loan Amount')),
                ('tenure', models.IntegerField(db_column='Tenure')),
                ('interest_rate', models.DecimalField(db_column='Interest Rate', decimal_places=2, max_digits=5)),
                ('monthly_payment', models.IntegerField(db_column='Monthly Payment')),
                ('emis_paid_on_time', models.IntegerField(db_column='EMIs paid on Time')),
                ('date_of_approval', models.DateField(db_column='Date of Approval')),
                ('end_date', models.DateField(db_column='End Date')),
                ('customer_id', models.ForeignKey(db_column='Customer ID', on_delete=django.db.models.deletion.CASCADE, to='users.customer')),
            ],
            options={
                'db_table': 'loan_data',
            },
        ),
    ]
